# Generated by Django 4.2.2 on 2024-07-16 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_contact_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectscount",
            name="experience",
            field=models.CharField(max_length=20),
        ),
    ]
