# Generated by Django 4.2.2 on 2024-07-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_alter_projectscount_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectsphoto",
            name="image",
            field=models.URLField(),
        ),
    ]
